# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: required
dist: trusty

# https://docs.travis-ci.com/user/installing-dependencies/#Installing-Packages-with-the-APT-Addon
addons:
  apt:
    packages:
      - google-chrome-stable

# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/
language: node_js
node_js:
  - "8"

# https://blog.travis-ci.com/2013-12-05-speed-up-your-builds-cache-your-dependencies
cache:
  yarn: true
  directories:
    - "node_modules"

notifications:
  email: false

# https://docs.travis-ci.com/user/deployment/npm/
deploy:
  api_key:
    secure: G9uFke1zNd2GWv1dCXshqf9T04jvyiPYKBAWWlYsf1dVUuCYNuy+E+aEGuNiNanb1tj4McADe48xANjMHSE09StFI85FWTg3aqGGAUIQ/ykxNNBIsxBtHp5aqSJGJ5aMVk9EXgsl0nl27hp2ITmMdNlSyQiyPFOHiJDUhfDndyY9FE+aqrD/5E8i/LPkJgHvYIkJAywrOcEchmagF4lRNGVyEW5sx8QwL0k1rwyUkGMaT8plC0jcM4nUQI4zfKSJSagax5sdL4Qaa7i+2HrhkXb1KA1aLq5XqXuLjSBe8f/BOeF19OE7p86jhJKOhu2nOEAEat9mpjtVVTM7dD6I9+s7qU9+nuPknRrZ/Vo5FM/QF0oalW4jm1NGmaI+A+7Xj28EUQgpyqO6HEEJuw6zGjrxr+9p7pcg6GC0Jb7SJwvYUFZqfMDdpU3era9SykC1GgfXzO0ddaxN68Yf7GE9TFzijz4WzQYz/j/5kWUP4zDDBlGxAY22l9XL42STX9u1Ye7fvxZw32qkfCklVL8rgApAq2k2h4QrrAfFIeMB+ecweh+e8W2pOmWI8g/6tgjs5CiG0q3bSpcWhv9ELy1XrTZQzSBQiM+ot6nDoCmT7YylKMsaR1Z/PYZz2ksUgfIyHQfWxtXRnAYxYx46f6CJGXJKyIv0PYrsuonEvfsoSDY=
  email:
    secure: ebkjitIl2U9R44e4p2f/O9PqaaMSEqQ5cEqzXgSzQH2ax8KKTIGl1W8H3HEQfn4KzhnQ4z6uphF8BlMskHvoZRNvV6JDyluw7W+K4LZos9g0v5tYo2kG4otCdfPVwxgSn+g6orWaJ7+czcB37W1Y4gPU278O6vx+4sVwhx0qoWn8NFDom6D4rZik+Dr1ctf1AkTmJGQzaZ9bEDhiHneq9wE/RUhd1r7Xo0zAXsZ2DHmJmjMt7b6wuWI3SuQxRnw56E7J4rQ6dl2ZGVhQgu7hd8UTJE0UrP2iVPDPQrAQMvBm8FlZHGBtvcI4CtOxvoHY8e1o3hcMK/1J80G2VolKCtT3OzhzqDFGQH15aogVQPR0E2YZ5HvCCsp5JJqtgiIKuTAhxbIIXd2PGPYYN/VCWXYsBn1gxVJIxn6HpOd6f2B6PJw3xsJRklDZmn6j+yWrdIHlZnCLdUM5cMDfWr8aiMHIeEobeJQckcHRMlkEiPxIFp/wiqLZUm0iU2kp66hnz/ntfiDLJw73tBZA7ME6zcY/7yiYZgv5B0KInMOh2JLCFia1gQD91izqopgOBMEdc3BCssma7GzMI7D4LjHeOTce+Nv1qXusnnKwYtPkuJQatqwpoMr7hePcWyOpoEa+JST7nMI+5z/Gu555WZKWM1NjMztEu+CPxRToP1FvwL8=
  provider: npm
  skip_cleanup: true
  on:
    tags: true
